version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: infra/docker/symfony/Dockerfile
    volumes:
      - ./Web_Application/Academy-LMS:/var/www/html:delegated
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "1"
      APP_PORT: 8000
      APP_URL: http://localhost:8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: academy
      DB_USERNAME: academy
      DB_PASSWORD: academy
      DB_ADMIN_USERNAME: root
      DB_ADMIN_PASSWORD: root
      DB_CREATE_DATABASE: "1"
      RUN_DB_SEED: "0"
      WARM_CACHES: "1"
      SKIP_COMPOSER_INSTALL: "0"
      SKIP_MIGRATIONS: "0"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: academy
      MYSQL_USER: academy
      MYSQL_PASSWORD: academy
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
