name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'Student Mobile APP/academy_lms_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Student Mobile APP/academy_lms_app'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter tests with coverage gate
        run: |
          flutter test --coverage
          python $GITHUB_WORKSPACE/tools/ci/enforce_lcov_coverage.py coverage/lcov.info 80 coverage/summary.json

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage-summary
          path: 'Student Mobile APP/academy_lms_app/coverage/summary.json'

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
